branches:
  only:
  - master
language: ruby
services:
- docker
before_script:
- repo=fingershock/socat
- builddate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
- buildrev=$(git rev-parse --short HEAD)
script:
- docker build --build-arg VCS_REF=$buildrev --build-arg BUILD_DATE=$builddate -t $repo:latest -f Dockerfile .
- socatver=$(docker run -t --rm $repo:latest -V | grep 'socat version ' | cut -d' ' -f3)
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $repo:latest
- vertags=$(ruby -e "ver=ARGV.first.split('/').last; (0..2).each {|i| puts ver.split('.')[0..i].join('.')}; puts ver;" $socatver)
- for ver in $vertags; do docker tag $repo:latest $repo:$ver; docker push $repo:$ver; done
